/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MuhammadDena;


import java.awt.Desktop;
import java.net.URL;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;

/**
 *
 * @author C03-0028
 */
public class FormPenjualan extends javax.swing.JFrame {

    public long total;
    public long bayar;
    public long kembali;
    public Statement st;
    Connection cn = Koneksi.getKoneksi();
            
    private DefaultTableModel model;
    /**
     * Creates new form FormPenjualan
     */
    public FormPenjualan() {
        initComponents();
        model = new DefaultTableModel();

        TabelBarang_Dena.setModel(model);
        model.addColumn("ID");
        model.addColumn("kode barang");
        model.addColumn("nama barang");
        model.addColumn("harga satuan");
        model.addColumn("jumlah beli");
        model.addColumn("harga");
        loadData();
        nofaktur();
        tampilpilih();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1_Dena = new javax.swing.JPanel();
        Label1_Dena = new javax.swing.JLabel();
        BBack_Dena = new javax.swing.JButton();
        Panel2_Dena = new javax.swing.JPanel();
        LabelHS_Dena = new javax.swing.JLabel();
        LabelKB_Dena = new javax.swing.JLabel();
        LabelJJ_Dena = new javax.swing.JLabel();
        TFieldKB_Dena = new javax.swing.JTextField();
        TFieldJJ_Dena = new javax.swing.JTextField();
        ScrollPane1_Dena = new javax.swing.JScrollPane();
        TabelBarang_Dena = new javax.swing.JTable();
        LabelNB_Dena = new javax.swing.JLabel();
        TFieldNF_Dena = new javax.swing.JTextField();
        ButtonTambah_Dena = new javax.swing.JButton();
        TFieldHS_Dena = new javax.swing.JTextField();
        LabelNF_Dena = new javax.swing.JLabel();
        CBoxNB_Dena = new javax.swing.JComboBox<>();
        TFieldH_Dena = new javax.swing.JTextField();
        ButtonHitung_Dena = new javax.swing.JButton();
        Panel3_Dena = new javax.swing.JPanel();
        LabelRp_Dena = new javax.swing.JLabel();
        TFieldTotal_Dena = new javax.swing.JTextField();
        ButtonTotal_Dena = new javax.swing.JButton();
        LabelBayar_Dena = new javax.swing.JLabel();
        TFieldBayar_Dena = new javax.swing.JTextField();
        LabelKembali_Dena = new javax.swing.JLabel();
        TFieldKembali_Dena = new javax.swing.JTextField();
        ButtonSelesai_Dena = new javax.swing.JButton();
        ButtonCetak_Dena = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("PENJUALAN");

        Panel1_Dena.setBackground(new java.awt.Color(0, 255, 255));

        Label1_Dena.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        Label1_Dena.setText("penjualan");

        BBack_Dena.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        BBack_Dena.setText("back");
        BBack_Dena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBack_DenaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel1_DenaLayout = new javax.swing.GroupLayout(Panel1_Dena);
        Panel1_Dena.setLayout(Panel1_DenaLayout);
        Panel1_DenaLayout.setHorizontalGroup(
            Panel1_DenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1_DenaLayout.createSequentialGroup()
                .addComponent(Label1_Dena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BBack_Dena)
                .addContainerGap())
        );
        Panel1_DenaLayout.setVerticalGroup(
            Panel1_DenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1_DenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Label1_Dena, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(BBack_Dena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel2_Dena.setBackground(new java.awt.Color(153, 153, 153));

        LabelHS_Dena.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        LabelHS_Dena.setText("harga SATUAN");

        LabelKB_Dena.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        LabelKB_Dena.setText("Kode barang");

        LabelJJ_Dena.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        LabelJJ_Dena.setText("JUMLAH jual");

        TabelBarang_Dena.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        TabelBarang_Dena.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KODE BARANG", "NAMA BARANG", "JUMLAH BARANG", "HARGA BELI", "HARGA JUAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelBarang_Dena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelBarang_DenaMouseClicked(evt);
            }
        });
        ScrollPane1_Dena.setViewportView(TabelBarang_Dena);

        LabelNB_Dena.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        LabelNB_Dena.setText("nama barang");

        ButtonTambah_Dena.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        ButtonTambah_Dena.setText("TAMBAH");
        ButtonTambah_Dena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambah_DenaActionPerformed(evt);
            }
        });

        LabelNF_Dena.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        LabelNF_Dena.setText("no faktur");

        CBoxNB_Dena.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Barang" }));
        CBoxNB_Dena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBoxNB_DenaActionPerformed(evt);
            }
        });

        ButtonHitung_Dena.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        ButtonHitung_Dena.setText("HITUNG");
        ButtonHitung_Dena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHitung_DenaActionPerformed(evt);
            }
        });

        Panel3_Dena.setBackground(new java.awt.Color(204, 204, 204));

        LabelRp_Dena.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N
        LabelRp_Dena.setText("Rp.");

        TFieldTotal_Dena.setBackground(new java.awt.Color(204, 204, 204));

        ButtonTotal_Dena.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        ButtonTotal_Dena.setText("TOTAL");
        ButtonTotal_Dena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTotal_DenaActionPerformed(evt);
            }
        });

        LabelBayar_Dena.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        LabelBayar_Dena.setText("bayar");

        TFieldBayar_Dena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFieldBayar_DenaActionPerformed(evt);
            }
        });
        TFieldBayar_Dena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFieldBayar_DenaKeyReleased(evt);
            }
        });

        LabelKembali_Dena.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        LabelKembali_Dena.setText("kembalian");

        ButtonSelesai_Dena.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        ButtonSelesai_Dena.setText("Selesai transaksi");
        ButtonSelesai_Dena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSelesai_DenaActionPerformed(evt);
            }
        });

        ButtonCetak_Dena.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        ButtonCetak_Dena.setText("cetak");
        ButtonCetak_Dena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCetak_DenaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel3_DenaLayout = new javax.swing.GroupLayout(Panel3_Dena);
        Panel3_Dena.setLayout(Panel3_DenaLayout);
        Panel3_DenaLayout.setHorizontalGroup(
            Panel3_DenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3_DenaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(Panel3_DenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonTotal_Dena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel3_DenaLayout.createSequentialGroup()
                        .addComponent(LabelRp_Dena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFieldTotal_Dena, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(Panel3_DenaLayout.createSequentialGroup()
                .addGroup(Panel3_DenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel3_DenaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Panel3_DenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelKembali_Dena)
                            .addComponent(LabelBayar_Dena))
                        .addGap(18, 18, 18)
                        .addGroup(Panel3_DenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFieldBayar_Dena)
                            .addComponent(TFieldKembali_Dena)))
                    .addGroup(Panel3_DenaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(ButtonSelesai_Dena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel3_DenaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonCetak_Dena, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        Panel3_DenaLayout.setVerticalGroup(
            Panel3_DenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3_DenaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(Panel3_DenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelRp_Dena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TFieldTotal_Dena))
                .addGap(18, 18, 18)
                .addComponent(ButtonTotal_Dena)
                .addGap(31, 31, 31)
                .addGroup(Panel3_DenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFieldBayar_Dena, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelBayar_Dena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel3_DenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelKembali_Dena)
                    .addComponent(TFieldKembali_Dena, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ButtonSelesai_Dena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonCetak_Dena)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Panel2_DenaLayout = new javax.swing.GroupLayout(Panel2_Dena);
        Panel2_Dena.setLayout(Panel2_DenaLayout);
        Panel2_DenaLayout.setHorizontalGroup(
            Panel2_DenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollPane1_Dena)
            .addGroup(Panel2_DenaLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(Panel2_DenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2_DenaLayout.createSequentialGroup()
                        .addGroup(Panel2_DenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelKB_Dena)
                            .addComponent(LabelNB_Dena)
                            .addComponent(LabelNF_Dena)
                            .addComponent(LabelHS_Dena)
                            .addComponent(LabelJJ_Dena))
                        .addGap(18, 18, 18)
                        .addGroup(Panel2_DenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFieldKB_Dena, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel2_DenaLayout.createSequentialGroup()
                                .addGroup(Panel2_DenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TFieldJJ_Dena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(TFieldHS_Dena, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFieldH_Dena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonHitung_Dena))
                            .addComponent(TFieldNF_Dena, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBoxNB_Dena, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(Panel3_Dena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(Panel2_DenaLayout.createSequentialGroup()
                        .addComponent(ButtonTambah_Dena, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Panel2_DenaLayout.setVerticalGroup(
            Panel2_DenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2_DenaLayout.createSequentialGroup()
                .addGroup(Panel2_DenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2_DenaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Panel3_Dena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel2_DenaLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(Panel2_DenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNF_Dena)
                            .addComponent(TFieldNF_Dena, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Panel2_DenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNB_Dena)
                            .addComponent(CBoxNB_Dena, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Panel2_DenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelKB_Dena)
                            .addComponent(TFieldKB_Dena, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Panel2_DenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelHS_Dena)
                            .addComponent(TFieldHS_Dena, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Panel2_DenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelJJ_Dena)
                            .addComponent(TFieldJJ_Dena, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Panel2_DenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFieldH_Dena, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonHitung_Dena))
                        .addGap(70, 70, 70)
                        .addComponent(ButtonTambah_Dena)))
                .addGap(1, 1, 1)
                .addComponent(ScrollPane1_Dena, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1_Dena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Panel2_Dena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel1_Dena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel2_Dena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BBack_DenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBack_DenaActionPerformed

        this.dispose();
    }//GEN-LAST:event_BBack_DenaActionPerformed

    private void CBoxNB_DenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBoxNB_DenaActionPerformed
        if (CBoxNB_Dena.getSelectedItem().equals("pilih barang")){
            TFieldKB_Dena.setText("");
            TFieldHS_Dena.setText("");
        }else{
        try {
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT kd_barang, jumlah_barang FROM tbl_barang WHERE nama_barang ='" + CBoxNB_Dena.getSelectedItem() + "'";
            ResultSet r = s.executeQuery(sql);
            while (r.next()) {
                TFieldKB_Dena.setText(r.getString("kd_barang"));
                TFieldJJ_Dena.setText(r.getString("jumlah_barang"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        try {
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT harga_jual FROM tbl_barang WHERE nama_barang ='" + CBoxNB_Dena.getSelectedItem() + "'";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                TFieldHS_Dena.setText(r.getString("harga_jual"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
        loadData();
    }//GEN-LAST:event_CBoxNB_DenaActionPerformed

    private void ButtonHitung_DenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHitung_DenaActionPerformed
    if(TFieldNF_Dena.getText().equals("") ||TFieldKB_Dena.getText().equals("") || CBoxNB_Dena.getSelectedItem().equals("")|| TFieldHS_Dena.getText().equals("")|| TFieldH_Dena.getText().equals("")){
            JOptionPane.showMessageDialog(null, "LENGKAPI DATA !", "Aplikasi Penjualan", JOptionPane.INFORMATION_MESSAGE);       
        }else{
        String a = TFieldH_Dena.getText();
            int aa = Integer.parseInt(a); 
        String b = TFieldJJ_Dena.getText();
            int bb = Integer.parseInt(b);
        if(aa > bb){
             JOptionPane.showMessageDialog(null, "jumlah melebihi stok", "Aplikasi Penjualan", JOptionPane.INFORMATION_MESSAGE);
             TFieldH_Dena.setText("");
        }else{
            if(TFieldH_Dena.getText().equals("")){
                JOptionPane.showMessageDialog(null, "ISI JUMLAH BELI !");
            }else{
                int jumlah, harga, total;
       
                jumlah = Integer.parseInt(TFieldH_Dena.getText().toString());
                harga = Integer.parseInt(TFieldHS_Dena.getText().toString());
                total = jumlah * harga;
                TFieldTotal_Dena.setText(Integer.toString(total));
            }
        }
        }  
    }//GEN-LAST:event_ButtonHitung_DenaActionPerformed

    private void ButtonTambah_DenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambah_DenaActionPerformed
    if(TFieldNF_Dena.getText().equals("") ||TFieldKB_Dena.getText().equals("") || CBoxNB_Dena.getSelectedItem().equals("")|| TFieldHS_Dena.getText().equals("")|| TFieldH_Dena.getText().equals("")|| TFieldTotal_Dena.getText().equals("")){
            JOptionPane.showMessageDialog(null, "LENGKAPI DATA !", "Aplikasi Penjualan", JOptionPane.INFORMATION_MESSAGE);    
        }else{
            String kdbarang = TFieldKB_Dena.getText();
            String nama_barang = (String)CBoxNB_Dena.getSelectedItem();
            String hsatuan = TFieldHS_Dena.getText();
            String jumlah_jual = TFieldH_Dena.getText();
            String harga = TFieldTotal_Dena.getText();   
            try {
                Connection c = Koneksi.getKoneksi();
                String sql = "INSERT INTO tbl_hitung_jual VALUES (?, ?, ?, ?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, null);
                p.setString(2, kdbarang);
                p.setString(3, nama_barang);
                p.setString(4, hsatuan);
                p.setString(5, jumlah_jual);
                p.setString(6, harga); 
                p.executeUpdate();
                p.close(); 
        } catch (SQLException e) {
            System.out.println("Terjadi Error");
            } finally {
                nofaktur();
                TFieldKB_Dena.setText("");
                CBoxNB_Dena.setSelectedItem("");
                TFieldHS_Dena.setText("");
                TFieldH_Dena.setText("");
                TFieldTotal_Dena.setText("");
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Aplikasi Penjualan", JOptionPane.INFORMATION_MESSAGE);
                loadData();
            }
        }
    }//GEN-LAST:event_ButtonTambah_DenaActionPerformed

    private void TabelBarang_DenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelBarang_DenaMouseClicked
      int jawaban;
        if ((jawaban = JOptionPane.showConfirmDialog(null,"Yakin batal?", "Konfirmasi", JOptionPane.YES_NO_OPTION)) == 0) {
        try{
        
        int i = TabelBarang_Dena.getSelectedRow();
        if (i == -1) {
            return;
        }
        String id = (String) model.getValueAt(i, 0);
        
        st = cn.createStatement();
        st.executeUpdate("delete from tbl_hitung_jual where id_hitung = '"+id+ "'");
        
        nofaktur();
        loadData();
        }catch(Exception e){
            e.printStackTrace();
        }
        }    
    }//GEN-LAST:event_TabelBarang_DenaMouseClicked

    private void ButtonTotal_DenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTotal_DenaActionPerformed
        try {
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();

            String sql = "SELECT SUM(`harga`) AS total FROM tbl_hitung_jual";
            ResultSet r = s.executeQuery(sql);
           
            while (r.next()) {
                TFieldTotal_Dena.setText(r.getString(""+"total"));
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error");
        }
 

    }//GEN-LAST:event_ButtonTotal_DenaActionPerformed

    private void ButtonSelesai_DenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSelesai_DenaActionPerformed
        if(TFieldBayar_Dena.getText().equals("") ||TFieldKembali_Dena.getText().equals("")){
            JOptionPane.showMessageDialog(null, "LENGKAPI DATA !", "Aplikasi Penjualan", JOptionPane.INFORMATION_MESSAGE);
        
        }else{
            String a = TFieldKembali_Dena.getText();
            int ab = Integer.parseInt(String.valueOf(TFieldKembali_Dena.getText()));
              if(ab < 0){
                JOptionPane.showMessageDialog(null, "Uang anda kurang", "Aplikasi Penjualan", JOptionPane.INFORMATION_MESSAGE);
                TFieldBayar_Dena.setText("");
            TFieldKembali_Dena.setText("");
              }else{
           try {
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();

            String sql = "SELECT * FROM tbl_hitung_jual";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                long millis=System.currentTimeMillis();  
                java.sql.Date date=new java.sql.Date(millis);  
                System.out.println(date); 
                String tgl = date.toString();
                String sqla = "INSERT INTO tbl_penjualan VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
         
                PreparedStatement p = c.prepareStatement(sqla);
                p.setString(1, TFieldNF_Dena.getText());
                p.setString(2, r.getString("kd_barang"));
                p.setString(3, r.getString("nama_barang"));
                p.setString(4, r.getString("hsatuan"));
                p.setString(5, r.getString("jumlah_jual"));
                p.setString(6, r.getString("harga"));
                p.setString(7, TFieldBayar_Dena.getText());
                p.setString(8, TFieldKembali_Dena.getText());
                p.setString(9, tgl);
                
                p.executeUpdate();
                p.close();
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error");
        }finally{
         try {
            String sqla ="TRUNCATE tbl_hitung_jual";
            java.sql.Connection conn=(Connection)Koneksi.getKoneksi();
            java.sql.PreparedStatement pst=conn.prepareStatement(sqla);
            pst.execute();
            JOptionPane.showMessageDialog(null, "TRANSAKSI SELESAI", "Aplikasi Penjualan", JOptionPane.INFORMATION_MESSAGE);
            loadData();
            TFieldNF_Dena.setText(TFieldNF_Dena.getText());
            TFieldBayar_Dena.setText("");
            TFieldKembali_Dena.setText("");
            TFieldTotal_Dena.setText("");
            nofaktur();
            ButtonCetak_Dena.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
           }
              }
         }
    }//GEN-LAST:event_ButtonSelesai_DenaActionPerformed

    private void TFieldBayar_DenaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFieldBayar_DenaKeyReleased
          bayar = Integer.parseInt(String.valueOf(TFieldBayar_Dena.getText()));
            total = Integer.parseInt(String.valueOf(TFieldTotal_Dena.getText()));
            kembali = bayar - total;
            
            TFieldKembali_Dena.setText(Long.toString(kembali)); 
    }//GEN-LAST:event_TFieldBayar_DenaKeyReleased

    private void TFieldBayar_DenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFieldBayar_DenaActionPerformed

    }//GEN-LAST:event_TFieldBayar_DenaActionPerformed

    private void ButtonCetak_DenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCetak_DenaActionPerformed
        try{
            Desktop.getDesktop().browse(new URL("http://localhost/PenjualanBarang/invoice.php?lap&fk="+ButtonCetak_Dena.getText()+"").toURI());
            } catch (Exception e){
                System.out.println(e);
            }
    }//GEN-LAST:event_ButtonCetak_DenaActionPerformed

    public final void loadData() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM tbl_hitung_jual";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                Object[] o = new Object[6];
                o[0] = r.getString("id_hitung");
                o[1] = r.getString("kd_barang");
                o[2] = r.getString("nama_barang");
                o[3] = r.getString("hsatuan");
                o[4] = r.getString("jumlah_jual");
                o[5] = r.getString("harga");       
                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error");
        }
    }
    
     private void tampilpilih() {
        try {
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();

            String sql = "SELECT nama_barang FROM tbl_barang WHERE jumlah_barang !='0'";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                CBoxNB_Dena.addItem(r.getString("nama_barang"));
            }

            r.last();
            int jumlahdata = r.getRow();
            r.first();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
     
     private void nofaktur() {
        try {
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();

            String sql = "SELECT * FROM tbl_penjualan ORDER by nofaktur desc";
            ResultSet r = s.executeQuery(sql);

            if (r.next()) {
                String nofak = r.getString("nofaktur").substring(1);
                String AN = "" + (Integer.parseInt(nofak) + 1);
                String Nol = "";

                if (AN.length() == 1) {
                    Nol = "000";
                } else if (AN.length() == 2) {
                    Nol = "00";
                } else if (AN.length() == 3) {
                    Nol = "0";
                } else if (AN.length() == 4) {
                    Nol = "";
                }

                TFieldNF_Dena.setText("F" + Nol + AN);
            } else {
                TFieldNF_Dena.setText("F0001");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void FilterHuruf(KeyEvent a){
        if(Character.isDigit(a.getKeyChar())){
            a.consume();
            JOptionPane.showMessageDialog(null, "masukan huruf saja!", "peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public void FilterAngka(KeyEvent a){
       if(Character.isAlphabetic(a.getKeyChar())){
           a.consume();
           JOptionPane.showMessageDialog(null, "masukan angka saja!", "peringatan", JOptionPane.WARNING_MESSAGE);
       }
    }


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBack_Dena;
    private javax.swing.JButton ButtonCetak_Dena;
    private javax.swing.JButton ButtonHitung_Dena;
    private javax.swing.JButton ButtonSelesai_Dena;
    private javax.swing.JButton ButtonTambah_Dena;
    private javax.swing.JButton ButtonTotal_Dena;
    private javax.swing.JComboBox<String> CBoxNB_Dena;
    private javax.swing.JLabel Label1_Dena;
    private javax.swing.JLabel LabelBayar_Dena;
    private javax.swing.JLabel LabelHS_Dena;
    private javax.swing.JLabel LabelJJ_Dena;
    private javax.swing.JLabel LabelKB_Dena;
    private javax.swing.JLabel LabelKembali_Dena;
    private javax.swing.JLabel LabelNB_Dena;
    private javax.swing.JLabel LabelNF_Dena;
    private javax.swing.JLabel LabelRp_Dena;
    private javax.swing.JPanel Panel1_Dena;
    private javax.swing.JPanel Panel2_Dena;
    private javax.swing.JPanel Panel3_Dena;
    private javax.swing.JScrollPane ScrollPane1_Dena;
    private javax.swing.JTextField TFieldBayar_Dena;
    private javax.swing.JTextField TFieldHS_Dena;
    private javax.swing.JTextField TFieldH_Dena;
    private javax.swing.JTextField TFieldJJ_Dena;
    private javax.swing.JTextField TFieldKB_Dena;
    private javax.swing.JTextField TFieldKembali_Dena;
    private javax.swing.JTextField TFieldNF_Dena;
    private javax.swing.JTextField TFieldTotal_Dena;
    private javax.swing.JTable TabelBarang_Dena;
    // End of variables declaration//GEN-END:variables
}
